version: '3'

services:
  airprint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: epson-airprint
    restart: unless-stopped
    # Using bridged network with explicit port mapping for macOS testing
    privileged: true # Required for CUPS to access USB devices (if needed)
    environment:
      - PRINTER_IP=${PRINTER_IP} # Epson L3250 IP address
      - PRINTER_NAME=${PRINTER_NAME}
      - PRINTER_LOCATION=${PRINTER_LOCATION}
      - PRINTER_INFO=${PRINTER_INFO}
      - HOST_NAME=${HOST_NAME} # Your host name (e.g., pi.local for Raspberry Pi)
      - CUPS_USER=${CUPS_USER} # User for CUPS web interface
      - CUPS_PASSWORD=${CUPS_PASSWORD} # Password for CUPS web interface
    # Add ports with "0" at the end to avoid conflicts with system ports
    ports:
      - "${CUPS_PORT}:631"
      - "${MDNS_PORT}:5353/udp" 

