version: '3'

services:
  airprint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: epson-airprint
    restart: unless-stopped
    hostname: ${HOST_NAME} # Set container hostname to match HOST_NAME
    network_mode: "host"  # Use host network for better mDNS/Avahi support
    privileged: true # Required for CUPS to access USB devices (if needed)
    environment:
      - PRINTER_IP=${PRINTER_IP} # Epson L3250 IP address
      - PRINTER_NAME=${PRINTER_NAME}
      - PRINTER_LOCATION=${PRINTER_LOCATION}
      - PRINTER_INFO=${PRINTER_INFO}
      - HOST_NAME=${HOST_NAME} # Your host name (e.g., pi.local for Raspberry Pi)
      - CUPS_USER=${CUPS_USER} # User for CUPS web interface
      - CUPS_PASSWORD=${CUPS_PASSWORD} # Password for CUPS web interface
